### ISSUE TITLE
Message d'erreur login

### ISSUE THREAD

**Issue by g-lgtm** [pg3io/pbo3#15]
* Retirer l'erreur de console et le gérer graphiquement en intégrant un message d'erreur expliquant que le user et / ou le mdp sont érronés.
* Gérer le non reload de la page si il y a erreur.

**Comment by lionelrs** [comment]
Si le nom d'utilisateur ou le mot de passe sont incorrectes le message 'Wrong username or password!' s'afiche sous les champs
