### ISSUE TITLE
supprimer le boolean "archived" sur le serveur

### ISSUE THREAD

**Issue by adri1s** [pg3io/pbo3#7]
Supprimer la valeur boolean _archived_ de Strapi et filtrer sur le faite que la change _archiveDate_ soit à NULL ou non

**Comment by lionelrs** [comment]
Ce n'est pas possible de supprimer le boolean 'archived' car 'archiveDate' ne pouvant pas etre NULL il faut un moyen de savoir si le serveur a ete archive ou pas.
